# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("helloworld.proto", :syntax => :proto3) do
    add_message "helloworld.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "helloworld.HelloReply" do
      optional :message, :string, 1
    end
    add_message "helloworld.JokeId" do
      optional :id, :int32, 1
    end
    add_message "helloworld.JokeBody" do
      optional :joke, :string, 1
    end
  end
end

module Helloworld
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.HelloReply").msgclass
  JokeId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.JokeId").msgclass
  JokeBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helloworld.JokeBody").msgclass
end
